"""add email verification and password reset

Revision ID: 8670875c55f7
Revises: 6f7f6f1abdd6
Create Date: 2026-05-05 05:50:01.179814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8670875c55f7'
down_revision = '6f7f6f1abdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email_verification_token'), ['email_verification_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token'))
        batch_op.drop_column('password_reset_sent_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('email_verification_sent_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
